default: &default
  app_url: "http://localhost:3000"
  user:
    validate:
      email:
        format: "\\A[\\w+\\-.]+@[a-z\\d\\-.]+\\.[a-z]+\\z"
        maxLength: 255
      user_name:
        maxLength: 50
      full_name:
        maxLength: 255
      password:
        minLength: 8
      telephone:
        format: "\\A(\\+84|0)(\\d{9,10})\\z"
  view:
    header:
      icon_size: 22
      icon_location_size: 35
      icon_arrow_down: 15
    item:
      icon_star_size: 15
      icon_heart_size: 18
    category:
      icon_category_size: 22
      icon_arrow_size: 16
    product_detail:
      icon_size: 24
      icon_check: 15
      star_count: 5
    cart:
      arrow_icon_size: 25
      trash_icon_size: 20
    order_lookup:
      status_icon_size: 20
      label_size: 25
      info_icon_size: 15
      phone_number:
        maxLength: 10
    user:
      menu_icon_size: 20
      eye_icon_size: 15
    admin:
      arrow_icon_size: 15
      search_icon_size: 20
      filter_icon_size: 28
  category:
    phone_id: 1
    laptop_id: 7
    audio_id: 12
  product:
    installment: 10
  order:
    delivery_fee: 15000
    order_status:
      canceled: 0
      pending: 1
      picking: 2
      shipping: 3
      delivered: 4
development:
  <<: *default
